spring:
  datasource:
    url: jdbc:mysql://localhost:3306/edu-word?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: admin@dev
    #指定数据连接沲
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 172.31.118.23
    password: 123456
    port: 6379
logging:
  level:
    com.talelife.edu.word: DEBUG
mybatis:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: com.talelife.edu.word.dao.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false